[package]
edition = "2024"
name = "openfootball_core"

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }

thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }